---
- name: install prerequisites for virtualbox kernel modules
  apt:
    name:
      - linux-headers-generic
      - linux-headers-{{ ansible_kernel }}
      - build-essential
      ## install dmg2img for handling MacOSX images
      - dmg2img

- name: add virtualbox signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: add virtualbox apt repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
    filename: virtualbox
    mode: 0644
    update_cache: true

- name: install virtualbox package
  apt:
    name: virtualbox-{{ virtualbox_version }}
...
